url: https://howardanguyen.com

# Site settings
title: "Howard Nguyen"
subtitle: "#!/howard/nguyen"
email: howardanguyen@gmail.com
description: "howard's personal portfolio"
keywords: "howard, nguyen, howard nguyen, hao, computer science, programming, Berkeley, Cal, Instagram, Facebook, Meta, ML, AI, Pinterest, LLM, GenAI"
favicon: "/favicon.ico?v=2"
google-tracking-id: "G-1249B4YPLM"
disqus-shortname: False


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# About variables
me-img: "/img/me.jpg"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/howardanguyen
  - title: linkedin
    url: https://www.linkedin.com/in/howardanguyen
  - title: github
    url: https://github.com/phoxelua

# Build settings
markdown: kramdown
permalink: pretty


destination: "site"
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", .git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md]
