url: https://howardanguyen.com1

# Site settings
title: "Howard Nguyen"
subtitle: "#!/howard/nguyen"
email: howardanguyen@gmail.com
description: "Personal website to host projects and portfolio for Howard Nguyen. Also a portfolio, maybe."
keywords: "howard, nguyen, howard nguyen, hao, computer science, programming, Berkeley, Cal, Captricity, Natero"
favicon: "/favicon.ico?v=2"
google-tracking-id: "UA-35880426-3"
disqus-shortname: False


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# About variables
me-img: "/img/me.jpg"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/howard.nguyen.94
  - title: google-plus
    url: https://plus.google.com/u/0/115660727961849929716/posts
  - title: linkedin
    url: http://www.linkedin.com/in/howardanguyen
  - title: stack-overflow
    url: http://stackoverflow.com/users/4493215/howard-nguyen
  - title: github
    url: http://github.com/phoxelua

# Build settings
markdown: kramdown
permalink: pretty


destination: "site"
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", .git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md]
